name: For each push and PR
on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: fake work
        run: |
          set -x
          num=0
          num=$((num+20))
          sleep 15
          num=$((num+20))
          sleep 15
          if ((num < 50)); then
            exit 0
          else
            exit 1
          fi
