name: For each commit and PR
on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: fake work
        run: |
          set -x
          command=false
          sleep 90
          echo hi
          if $command; then
            exit 1
          else
            exit 0
          fi
