name: For each commit and PR
on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: fake work
        run: |
          set -x
          num=0
          num=$((num+10))
          sleep 45
          num=$((num+10))
          sleep 45
          if ((num < 30)); then
            exit 0
          else
            exit 1
          fi
